<?php

return [
    'default_city' => 'Jaraguá do Sul',

    'cities' => [
        'jaragua_do_sul' => [
            'name' => 'Jaraguá do Sul',
            'neighborhoods' => [
                'Água Verde',
                'Águas Claras',
                'Amizade',
                'Barra do Rio Cerro',
                'Barra do Rio Molha',
                'Boa Vista',
                'Braço do Ribeirão Cavalo',
                'Centenário',
                'Centro',
                'Chico de Paulo',
                'Czerniewicz',
                'Estrada Nova',
                'Ilha da Figueira',
                'Jaraguá 84',
                'Jaraguá 99',
                'Jaraguá Esquerdo',
                'João Pessoa',
                'Nereu Ramos',
                'Nova Brasília',
                'Parque Malwee',
                'Rau',
                'Ribeirão Cavalo',
                'Rio Cerro I',
                'Rio Cerro II',
                'Rio da Luz',
                'Rio Molha',
                'Santa Luzia',
                'Santo Antônio',
                'São Luís',
                'Tifa Martins',
                'Tifa Monos',
                'Três Rios do Norte',
                'Três Rios do Sul',
                'Vieira',
                'Vila Baependi',
                'Vila Lalau',
                'Vila Lenzi',
                'Vila Nova',
            ],
            'aliases' => [
                'Água Verde' => ['Agua Verde', 'Águas Verdes', 'Aguas Verdes'],
                'Águas Claras' => ['Aguas Claras'],
                'Barra do Rio Cerro' => ['Rio Cerro', 'Barra'],
                'Barra do Rio Molha' => ['Rio Molha', 'Barra Molha'],
                'Boa Vista' => ['Boa Vista Jaraguá', 'Boa Vista Jaragua'],
                'Braço do Ribeirão Cavalo' => ['Braco do Ribeirao Cavalo', 'Braço do Ribeirão', 'Braco do Ribeirao', 'Bracinho'],
                'Centenário' => ['Centenario'],
                'Centro' => ['Bairro Centro', 'Centro da Cidade'],
                'Chico de Paulo' => ['Chico de Paula', 'Chico'],
                'Czerniewicz' => ['Czernievicz', 'Czerniewitz', 'Czern', 'Vila Czerniewicz'],
                'Estrada Nova' => ['Est Nova', 'Estrada Nova Jaraguá'],
                'Ilha da Figueira' => ['Figueira', 'Ilha'],
                'Jaraguá 84' => ['Jaragua 84', '84'],
                'Jaraguá 99' => ['Jaragua 99'],
                'Jaraguá Esquerdo' => ['Jaragua Esquerdo', 'Esquerdo'],
                'João Pessoa' => ['Joao Pessoa'],
                'Nereu Ramos' => ['Nereu'],
                'Nova Brasília' => ['Nova Brasilia'],
                'Parque Malwee' => ['Malwee'],
                'Rau' => ['Vila Rau'],
                'Ribeirão Cavalo' => ['Ribeirao Cavalo'],
                'Rio Cerro I' => ['Rio Cerro Primeiro', 'Rio Cerro 1', 'Rio Cerro Um'],
                'Rio Cerro II' => ['Rio Cerro Segundo', 'Chocoleite', 'Rio Cerro 2', 'Rio Cerro Dois'],
                'Rio da Luz' => ['Rio da Cachoeira'],
                'Santa Luzia' => ['Vila Santa Luzia', 'Santa Lucia'],
                'Santo Antônio' => ['Santo Antonio'],
                'São Luís' => ['São Luiz', 'Sao Luis', 'Sao Luiz'],
                'Tifa Martins' => ['Ana Paula', 'Martins'],
                'Tifa Monos' => ['Monos'],
                'Três Rios do Norte' => ['Tres Rios do Norte', '3 Rios do Norte', '3Rios Norte'],
                'Três Rios do Sul' => ['Tres Rios do Sul', '3 Rios do Sul', '3Rios Sul'],
                'Vieira' => ['Vieiras'],
                'Vila Baependi' => ['Baependi'],
                'Vila Lalau' => ['Lalau'],
                'Vila Lenzi' => ['Lenzi'],
                'Vila Nova' => ['Vila Nova Jaraguá', 'Vila Nova Jaragua'],
            ],
        ],
    ],

    'references' => [
        'jaragua_do_sul' => [
            'centro' => [
                'aliases' => [
                    'centro',
                    'região central',
                    'regiao central',
                    'perto do centro',
                    'redondezas do centro',
                    'arredores do centro',
                    'no centro',
                    'área central',
                    'area central',
                    'bairro centro',
                    'coração da cidade',
                    'coracao da cidade',
                    'meio da cidade',
                    'miolo da cidade',
                    'centrinho',
                ],
                'bairros' => [
                    'Centro',
                    'Vila Lenzi',
                    'Nova Brasília',
                    'Czerniewicz',
                    'Vila Baependi',
                    'Vila Lalau',
                    'Jaraguá Esquerdo',
                ],
                'city' => 'Jaraguá do Sul',
            ],
            'parque_malwee' => [
                'aliases' => [
                    'parque malwee',
                    'malwee',
                    'parque da malwee',
                    'perto do malwee',
                    'próximo ao malwee',
                    'proximo ao malwee',
                    'região do malwee',
                    'regiao do malwee',
                    'arredores do parque malwee',
                    'parque ecológico malwee',
                    'parque ecologico malwee',
                ],
                'bairros' => ['Parque Malwee', 'Vieira', 'Rio Molha'],
                'city' => 'Jaraguá do Sul',
            ],
            'chocoleite' => [
                'aliases' => [
                    'chocoleite',
                    'empresa chocoleite',
                    'perto da chocoleite',
                    'próximo a chocoleite',
                    'proximo a chocoleite',
                    'região da chocoleite',
                    'regiao da chocoleite',
                    'fábrica chocoleite',
                    'fabrica chocoleite',
                    'indústria chocoleite',
                    'industria chocoleite',
                ],
                'bairros' => ['Rio Cerro II', 'Rio Cerro I', 'Barra do Rio Cerro'],
                'city' => 'Jaraguá do Sul',
            ],
            'weg' => [
                'aliases' => [
                    'weg',
                    'perto da weg',
                    'próximo a weg',
                    'proximo a weg',
                    'empresa weg',
                    'fábrica weg',
                    'fabrica weg',
                    'região da weg',
                    'regiao da weg',
                    'motor elétrico',
                    'motor eletrico',
                    'indústria weg',
                    'industria weg',
                    'parque fabril',
                ],
                'bairros' => ['Centro', 'Vila Lenzi', 'Nova Brasília', 'Czerniewicz'],
                'city' => 'Jaraguá do Sul',
            ],
            'weg_ii' => [
                'aliases' => [
                    'weg ii',
                    'weg 2',
                    'weg dois',
                    'weg barra',
                    'weg rio cerro',
                    'fábrica rio cerro',
                    'fabrica rio cerro',
                ],
                'bairros' => ['Rio Cerro II', 'Rio Cerro I', 'Barra do Rio Cerro'],
                'city' => 'Jaraguá do Sul',
            ],
            'shopping' => [
                'aliases' => [
                    'shopping',
                    'park shopping',
                    'shopping jaraguá',
                    'shopping jaragua',
                    'jaraguá park shopping',
                    'jaragua park shopping',
                    'perto do shopping',
                    'próximo ao shopping',
                    'proximo ao shopping',
                    'centro comercial',
                ],
                'bairros' => ['Centro', 'Vila Lenzi', 'Nova Brasília', 'Czerniewicz'],
                'city' => 'Jaraguá do Sul',
            ],
            'breithaupt' => [
                'aliases' => [
                    'breithaupt',
                    'breit',
                    'galeria breithaupt',
                    'perto do breithaupt',
                    'próximo ao breithaupt',
                    'proximo ao breithaupt',
                    'rua coronel procópio',
                    'rua coronel procopio',
                ],
                'bairros' => ['Centro', 'Vila Lenzi'],
                'city' => 'Jaraguá do Sul',
            ],
            'hospital' => [
                'aliases' => [
                    'hospital',
                    'hospital são josé',
                    'hospital sao jose',
                    'hospital são jose',
                    'hospital jaraguá',
                    'hospital jaragua',
                    'perto do hospital',
                    'próximo ao hospital',
                    'proximo ao hospital',
                    'são josé',
                    'sao jose',
                    'posto de saúde',
                    'posto de saude',
                    'pronto socorro',
                    'pronto atendimento',
                ],
                'bairros' => ['Centro', 'Vila Lenzi', 'Nova Brasília'],
                'city' => 'Jaraguá do Sul',
            ],
            'rodoviaria' => [
                'aliases' => [
                    'rodoviária',
                    'rodoviaria',
                    'terminal rodoviário',
                    'terminal rodoviario',
                    'terminal',
                    'estação rodoviária',
                    'estacao rodoviaria',
                    'ônibus',
                    'onibus',
                    'perto da rodoviária',
                    'perto da rodoviaria',
                ],
                'bairros' => ['Centro', 'Vila Lenzi'],
                'city' => 'Jaraguá do Sul',
            ],
            'arena_jaragua' => [
                'aliases' => [
                    'arena jaraguá',
                    'arena jaragua',
                    'arena',
                    'ginásio',
                    'ginasio',
                    'perto da arena',
                    'ginásio de esportes',
                    'ginasio de esportes',
                ],
                'bairros' => ['Centro', 'Nova Brasília', 'Vila Lenzi', 'Czerniewicz'],
                'city' => 'Jaraguá do Sul',
            ],
            'scar' => [
                'aliases' => [
                    'scar',
                    'centro cultural',
                    'centro cultural scar',
                    'sociedade cultura artística',
                    'sociedade cultura artistica',
                    'teatro scar',
                    'perto do scar',
                ],
                'bairros' => ['Centro', 'Vila Lenzi'],
                'city' => 'Jaraguá do Sul',
            ],
            'ifsc' => [
                'aliases' => [
                    'ifsc',
                    'instituto federal',
                    'instituto federal de santa catarina',
                    'ifsc campus jaraguá',
                    'ifsc campus jaragua',
                    'perto do ifsc',
                    'campus ifsc',
                ],
                'bairros' => ['Rau', 'Nova Brasília', 'Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'senai' => [
                'aliases' => [
                    'senai',
                    'escola técnica',
                    'escola tecnica',
                    'escola do senai',
                    'perto do senai',
                    'senai jaraguá',
                    'senai jaragua',
                    'curso profissionalizante',
                ],
                'bairros' => ['Czerniewicz', 'Vila Lenzi', 'Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'unesc' => [
                'aliases' => [
                    'católica',
                    'catolica',
                    'católica sc',
                    'catolica sc',
                    'universidade católica',
                    'universidade catolica',
                    'universidade',
                    'faculdade',
                    'perto da universidade',
                    'perto da católica',
                    'perto da catolica',
                    'campus universitário',
                    'campus universitario',
                ],
                'bairros' => ['Centro', 'Vila Lenzi', 'Rau'],
                'city' => 'Jaraguá do Sul',
            ],
            'zona_norte' => [
                'aliases' => [
                    'zona norte',
                    'região norte',
                    'regiao norte',
                    'parte norte',
                    'lado norte',
                    'norte da cidade',
                    'área norte',
                    'area norte',
                ],
                'bairros' => [
                    'Barra do Rio Cerro',
                    'Rio Cerro I',
                    'Rio Cerro II',
                    'Rio da Luz',
                    'Rio Molha',
                    'Amizade',
                    'Santa Luzia',
                    'Três Rios do Norte',
                    'Santo Antônio',
                ],
                'city' => 'Jaraguá do Sul',
            ],
            'zona_sul' => [
                'aliases' => [
                    'zona sul',
                    'região sul',
                    'regiao sul',
                    'parte sul',
                    'lado sul',
                    'sul da cidade',
                    'área sul',
                    'area sul',
                ],
                'bairros' => [
                    'Água Verde',
                    'Águas Claras',
                    'Boa Vista',
                    'Jaraguá 84',
                    'Jaraguá 99',
                    'Três Rios do Sul',
                    'Vila Nova',
                ],
                'city' => 'Jaraguá do Sul',
            ],
            'bairro_da_juventude' => [
                'aliases' => [
                    'bairro da juventude',
                    'perto do bairro da juventude',
                ],
                'bairros' => ['Rau', 'João Pessoa'],
                'city' => 'Jaraguá do Sul',
            ],
            'parque_eventos' => [
                'aliases' => [
                    'parque de eventos',
                    'parque eventos',
                    'parque admar',
                    'admar josé batschauer',
                    'admar jose batschauer',
                    'schützenfest',
                    'schutzenfest',
                    'festa do tiro',
                    'festa das flores',
                    'perto do parque de eventos',
                ],
                'bairros' => ['Nova Brasília', 'Vila Lenzi', 'Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'rio_cerro' => [
                'aliases' => [
                    'rio cerro',
                    'região do rio cerro',
                    'regiao do rio cerro',
                    'bairros do rio cerro',
                    'grande rio cerro',
                ],
                'bairros' => ['Rio Cerro I', 'Rio Cerro II', 'Barra do Rio Cerro'],
                'city' => 'Jaraguá do Sul',
            ],
            'grande_agua_verde' => [
                'aliases' => [
                    'grande água verde',
                    'grande agua verde',
                    'região da água verde',
                    'regiao da agua verde',
                    'arredores água verde',
                    'arredores agua verde',
                ],
                'bairros' => ['Água Verde', 'Águas Claras', 'Boa Vista', 'Vila Nova'],
                'city' => 'Jaraguá do Sul',
            ],
            'br_280' => [
                'aliases' => [
                    'br 280',
                    'br-280',
                    'br280',
                    'rodovia',
                    'beira da br',
                    'marginal br',
                    'perto da br 280',
                    'próximo a br 280',
                ],
                'bairros' => ['Água Verde', 'Vila Nova', 'Centro', 'Rau'],
                'city' => 'Jaraguá do Sul',
            ],
            'igreja_matriz' => [
                'aliases' => [
                    'igreja matriz',
                    'igreja são sebastião',
                    'igreja sao sebastiao',
                    'catedral',
                    'catedral são sebastião',
                    'catedral sao sebastiao',
                    'matriz são sebastião',
                    'matriz sao sebastiao',
                    'perto da igreja',
                    'perto da catedral',
                    'igreja católica',
                    'igreja catolica',
                ],
                'bairros' => ['Centro', 'Vila Lenzi'],
                'city' => 'Jaraguá do Sul',
            ],
            'biblioteca_municipal' => [
                'aliases' => [
                    'biblioteca',
                    'biblioteca pública',
                    'biblioteca publica',
                    'biblioteca municipal',
                    'biblioteca rui barbosa',
                    'biblioteca da estação',
                    'biblioteca da estacao',
                ],
                'bairros' => ['Centro', 'Vila Lenzi'],
                'city' => 'Jaraguá do Sul',
            ],
            'casa_friedel' => [
                'aliases' => [
                    'casa friedel',
                    'casa enxaimel',
                    'casa histórica',
                    'casa historica',
                    'casa antiga',
                    'museu friedel',
                    'museu enxaimel',
                ],
                'bairros' => ['Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'femusc' => [
                'aliases' => [
                    'femusc',
                    'festival de música',
                    'festival de musica',
                    'festival de santa catarina',
                    'perto do femusc',
                ],
                'bairros' => ['Centro', 'Vila Lenzi'],
                'city' => 'Jaraguá do Sul',
            ],
            'cima' => [
                'aliases' => [
                    'cima',
                    'centro interpretativo',
                    'centro interpretativo mata atlântica',
                    'centro interpretativo mata atlantica',
                    'mata atlântica',
                    'mata atlantica',
                    'reserva ambiental',
                    'trilha interpretativa',
                    'instituto rã bugio',
                    'instituto ra bugio',
                ],
                'bairros' => ['Barra do Rio Cerro'],
                'city' => 'Jaraguá do Sul',
            ],
            'morro_boa_vista' => [
                'aliases' => [
                    'morro boa vista',
                    'morro',
                    'boa vista',
                    'vista panorâmica',
                    'vista panoramica',
                    'perto do morro',
                    'topo do morro',
                    'subida do morro',
                ],
                'bairros' => ['Boa Vista', 'Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'maria_fumaca' => [
                'aliases' => [
                    'maria fumaça',
                    'maria fumaca',
                    'trem turístico',
                    'trem turistico',
                    'passeio de trem',
                    'trem da serra',
                    'abpf',
                    'ferrovia turística',
                    'ferrovia turistica',
                ],
                'bairros' => ['Centro', 'Vila Lenzi', 'Vila Baependi'],
                'city' => 'Jaraguá do Sul',
            ],
            'estacao_ferroviaria' => [
                'aliases' => [
                    'estação ferroviária',
                    'estacao ferroviaria',
                    'estação de trem',
                    'estacao de trem',
                    'antiga estação',
                    'antiga estacao',
                    'estação histórica',
                    'estacao historica',
                ],
                'bairros' => ['Centro', 'Vila Lenzi'],
                'city' => 'Jaraguá do Sul',
            ],
            'centro_historico' => [
                'aliases' => [
                    'centro histórico',
                    'centro historico',
                    'região histórica',
                    'regiao historica',
                    'patrimônio histórico',
                    'patrimonio historico',
                    'casarões antigos',
                    'casaroes antigos',
                ],
                'bairros' => ['Centro', 'Vila Lenzi'],
                'city' => 'Jaraguá do Sul',
            ],
            'marisol' => [
                'aliases' => [
                    'marisol',
                    'empresa marisol',
                    'fábrica marisol',
                    'fabrica marisol',
                    'indústria marisol',
                    'industria marisol',
                    'perto da marisol',
                    'próximo a marisol',
                    'proximo a marisol',
                ],
                'bairros' => ['Rau', 'João Pessoa', 'Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'duas_rodas' => [
                'aliases' => [
                    'duas rodas',
                    'empresa duas rodas',
                    'fábrica duas rodas',
                    'fabrica duas rodas',
                    'indústria duas rodas',
                    'industria duas rodas',
                    'perto da duas rodas',
                    'próximo a duas rodas',
                    'proximo a duas rodas',
                ],
                'bairros' => ['Rau', 'Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'partage_shopping' => [
                'aliases' => [
                    'partage',
                    'shopping partage',
                    'partage shopping',
                    'partage jaraguá',
                    'partage jaragua',
                    'shopping da estação',
                    'shopping da estacao',
                    'perto do partage',
                    'próximo ao partage',
                    'proximo ao partage',
                ],
                'bairros' => ['Centro', 'Vila Lenzi'],
                'city' => 'Jaraguá do Sul',
            ],
            'zona_leste' => [
                'aliases' => [
                    'zona leste',
                    'região leste',
                    'regiao leste',
                    'parte leste',
                    'lado leste',
                    'leste da cidade',
                    'área leste',
                    'area leste',
                ],
                'bairros' => [
                    'João Pessoa',
                    'Nereu Ramos',
                    'Ilha da Figueira',
                    'Estrada Nova',
                    'São Luís',
                ],
                'city' => 'Jaraguá do Sul',
            ],
            'regiao_ribeirao' => [
                'aliases' => [
                    'região ribeirão',
                    'regiao ribeirao',
                    'ribeirão cavalo',
                    'ribeirao cavalo',
                    'região do ribeirão',
                    'regiao do ribeirao',
                    'braço do ribeirão',
                    'braco do ribeirao',
                ],
                'bairros' => ['Ribeirão Cavalo', 'Braço do Ribeirão Cavalo', 'São Luís'],
                'city' => 'Jaraguá do Sul',
            ],
            'garibaldi' => [
                'aliases' => [
                    'garibaldi',
                    'região garibaldi',
                    'regiao garibaldi',
                    'comunidade garibaldi',
                ],
                'bairros' => ['Centenário', 'São Luís', 'Braço do Ribeirão Cavalo'],
                'city' => 'Jaraguá do Sul',
            ],
            'prefeitura' => [
                'aliases' => [
                    'prefeitura',
                    'prefeitura municipal',
                    'sede da prefeitura',
                    'paço municipal',
                    'paço da prefeitura',
                    'paco municipal',
                    'paco da prefeitura',
                    'perto da prefeitura',
                ],
                'bairros' => ['Barra do Rio Molha', 'Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'camara_vereadores' => [
                'aliases' => [
                    'câmara de vereadores',
                    'camara de vereadores',
                    'câmara municipal',
                    'camara municipal',
                    'legislativo',
                    'perto da câmara',
                    'perto da camara',
                ],
                'bairros' => ['Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'forum' => [
                'aliases' => [
                    'fórum',
                    'forum',
                    'fórum da comarca',
                    'forum da comarca',
                    'justiça',
                    'justica',
                    'perto do fórum',
                    'perto do forum',
                ],
                'bairros' => ['Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'policia_militar' => [
                'aliases' => [
                    'polícia militar',
                    'policia militar',
                    'pm',
                    'batalhão',
                    'batalhao',
                    'perto da pm',
                    'quartel',
                    'perto do quartel',
                ],
                'bairros' => ['Centro', 'Nova Brasília'],
                'city' => 'Jaraguá do Sul',
            ],
            'corpo_bombeiros' => [
                'aliases' => [
                    'corpo de bombeiros',
                    'bombeiros',
                    'bombeiro',
                    'perto dos bombeiros',
                    'perto do bombeiro',
                ],
                'bairros' => ['Centro', 'Nova Brasília'],
                'city' => 'Jaraguá do Sul',
            ],
            'delegacia' => [
                'aliases' => [
                    'delegacia',
                    'polícia civil',
                    'policia civil',
                    'perto da delegacia',
                    'distrito policial',
                ],
                'bairros' => ['Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'aeroporto' => [
                'aliases' => [
                    'aeroporto',
                    'aeródromo',
                    'aerodromo',
                    'aeroporto regional',
                    'pista de pouso',
                    'perto do aeroporto',
                    'voo executivo',
                ],
                'bairros' => ['Rau', 'Água Verde', 'Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'samae' => [
                'aliases' => [
                    'samae',
                    'companhia de água',
                    'companhia de agua',
                    'tratamento de água',
                    'tratamento de agua',
                    'perto do samae',
                ],
                'bairros' => ['Centro', 'Nova Brasília'],
                'city' => 'Jaraguá do Sul',
            ],
            'upa' => [
                'aliases' => [
                    'upa',
                    'upa 24h',
                    'upa 24 horas',
                    'unidade de pronto atendimento',
                    'pronto atendimento 24h',
                    'perto da upa',
                    'emergência',
                    'emergencia',
                ],
                'bairros' => ['Nova Brasília', 'Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'posto_saude' => [
                'aliases' => [
                    'posto de saúde',
                    'posto de saude',
                    'ubs',
                    'unidade básica de saúde',
                    'unidade basica de saude',
                    'centro de saúde',
                    'centro de saude',
                    'perto do posto',
                ],
                'bairros' => ['Centro', 'Nova Brasília', 'Vila Lenzi'],
                'city' => 'Jaraguá do Sul',
            ],
            'correios' => [
                'aliases' => [
                    'correios',
                    'agência dos correios',
                    'agencia dos correios',
                    'perto dos correios',
                    'carteiro',
                ],
                'bairros' => ['Centro', 'Vila Lenzi'],
                'city' => 'Jaraguá do Sul',
            ],
            'banco_brasil' => [
                'aliases' => [
                    'banco do brasil',
                    'bb',
                    'agência bb',
                    'agencia bb',
                    'perto do banco do brasil',
                    'perto do bb',
                ],
                'bairros' => ['Centro', 'Vila Lenzi'],
                'city' => 'Jaraguá do Sul',
            ],
            'caixa_economica' => [
                'aliases' => [
                    'caixa econômica',
                    'caixa economica',
                    'caixa',
                    'cef',
                    'agência caixa',
                    'agencia caixa',
                    'perto da caixa',
                    'perto da caixa econômica',
                    'perto da caixa economica',
                ],
                'bairros' => ['Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'inss' => [
                'aliases' => [
                    'inss',
                    'previdência',
                    'previdencia',
                    'instituto nacional',
                    'aposentadoria',
                    'perto do inss',
                ],
                'bairros' => ['Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'receita_federal' => [
                'aliases' => [
                    'receita federal',
                    'receita',
                    'imposto de renda',
                    'irpf',
                    'perto da receita',
                    'perto da receita federal',
                ],
                'bairros' => ['Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'supermercado' => [
                'aliases' => [
                    'supermercado',
                    'mercado',
                    'super',
                    'perto do mercado',
                    'perto do supermercado',
                    'compras',
                ],
                'bairros' => ['Centro', 'Vila Lenzi', 'Nova Brasília', 'Czerniewicz'],
                'city' => 'Jaraguá do Sul',
            ],
            'giassi' => [
                'aliases' => [
                    'giassi',
                    'supermercado giassi',
                    'mercado giassi',
                    'perto do giassi',
                ],
                'bairros' => ['Centro', 'Nova Brasília'],
                'city' => 'Jaraguá do Sul',
            ],
            'angeloni' => [
                'aliases' => [
                    'angeloni',
                    'supermercado angeloni',
                    'mercado angeloni',
                    'perto do angeloni',
                ],
                'bairros' => ['Centro', 'Vila Lenzi'],
                'city' => 'Jaraguá do Sul',
            ],
            'cooper' => [
                'aliases' => [
                    'cooper',
                    'supermercado cooper',
                    'mercado cooper',
                    'cooperativa',
                    'cooper jaraguá',
                    'cooper jaragua',
                    'perto da cooper',
                    'perto do cooper',
                ],
                'bairros' => ['Centro', 'Nova Brasília', 'Rau'],
                'city' => 'Jaraguá do Sul',
            ],
            'bretzke' => [
                'aliases' => [
                    'bretzke',
                    'bretz',
                    'empresa bretzke',
                    'alimentos bretzke',
                    'fábrica bretzke',
                    'fabrica bretzke',
                ],
                'bairros' => ['Rau', 'Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'arroz_urbano' => [
                'aliases' => [
                    'arroz urbano',
                    'empresa arroz urbano',
                    'fábrica arroz',
                    'fabrica arroz',
                    'beneficiadora arroz',
                ],
                'bairros' => ['Rau', 'Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'rio_itapocu' => [
                'aliases' => [
                    'rio itapocu',
                    'rio itapocú',
                    'beira rio',
                    'beira do rio',
                    'margem do rio',
                    'perto do rio',
                    'próximo ao rio',
                    'proximo ao rio',
                    'itapocu',
                ],
                'bairros' => [
                    'Centro',
                    'Nova Brasília',
                    'Vila Lenzi',
                    'Barra do Rio Cerro',
                    'Barra do Rio Molha',
                    'Água Verde',
                ],
                'city' => 'Jaraguá do Sul',
            ],
            'vale_itapocu' => [
                'aliases' => [
                    'vale do itapocu',
                    'região itapocu',
                    'regiao itapocu',
                    'vale do itapocú',
                ],
                'bairros' => [
                    'Barra do Rio Cerro',
                    'Rio Cerro I',
                    'Rio Cerro II',
                    'Rio da Luz',
                    'Rio Molha',
                    'Amizade',
                    'Centro',
                    'Nova Brasília',
                ],
                'city' => 'Jaraguá do Sul',
            ],
            'sc_110' => [
                'aliases' => [
                    'sc 110',
                    'sc-110',
                    'sc110',
                    'rodovia sc 110',
                    'portal',
                    'portal da cidade',
                    'entrada da cidade',
                    'perto do portal',
                    'fritz bartel',
                ],
                'bairros' => ['Nova Brasília', 'Vila Lenzi', 'Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'sc_108' => [
                'aliases' => [
                    'sc 108',
                    'sc-108',
                    'sc108',
                    'rodovia sc 108',
                    'estrada joinville',
                    'estrada blumenau',
                    'perto da sc 108',
                ],
                'bairros' => ['Ilha da Figueira', 'João Pessoa', 'Nereu Ramos'],
                'city' => 'Jaraguá do Sul',
            ],
            'parque_inovacao' => [
                'aliases' => [
                    'parque da inovação',
                    'parque da inovacao',
                    'parque inovação',
                    'parque inovacao',
                    'centro de inovação',
                    'centro de inovacao',
                    'perto do parque inovação',
                ],
                'bairros' => ['Centro', 'Nova Brasília'],
                'city' => 'Jaraguá do Sul',
            ],
            'museu_historico' => [
                'aliases' => [
                    'museu',
                    'museu histórico',
                    'museu historico',
                    'museu emílio da silva',
                    'museu emilio da silva',
                    'museu da cidade',
                    'perto do museu',
                ],
                'bairros' => ['Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'orquestra_filarmonica' => [
                'aliases' => [
                    'orquestra',
                    'orquestra filarmônica',
                    'orquestra filarmonica',
                    'filarmônica',
                    'filarmonica',
                    'música para todos',
                    'musica para todos',
                    'escola de música',
                    'escola de musica',
                ],
                'bairros' => ['Centro', 'Vila Lenzi'],
                'city' => 'Jaraguá do Sul',
            ],
            'jaragua_futsal' => [
                'aliases' => [
                    'jaraguá futsal',
                    'jaragua futsal',
                    'futsal',
                    'quadra de futsal',
                    'associação desportiva',
                    'associacao desportiva',
                    'time de futsal',
                    'perto do futsal',
                ],
                'bairros' => ['Centro', 'Nova Brasília'],
                'city' => 'Jaraguá do Sul',
            ],
            'defesa_civil' => [
                'aliases' => [
                    'defesa civil',
                    'proteção civil',
                    'protecao civil',
                    'perto da defesa civil',
                ],
                'bairros' => ['Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'cartorio' => [
                'aliases' => [
                    'cartório',
                    'cartorio',
                    'cartório eleitoral',
                    'cartorio eleitoral',
                    'cartório de registro',
                    'cartorio de registro',
                    'perto do cartório',
                    'perto do cartorio',
                ],
                'bairros' => ['Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'terminal_urbano' => [
                'aliases' => [
                    'terminal urbano',
                    'terminal de ônibus',
                    'terminal de onibus',
                    'terminal municipal',
                    'ponto de ônibus central',
                    'ponto de onibus central',
                    'perto do terminal',
                    'terminal getúlio vargas',
                    'terminal getulio vargas',
                ],
                'bairros' => ['Centro', 'Vila Lenzi'],
                'city' => 'Jaraguá do Sul',
            ],
            'praca_central' => [
                'aliases' => [
                    'praça',
                    'praca',
                    'praça central',
                    'praca central',
                    'praça ângela piazera',
                    'praca angela piazera',
                    'praça principal',
                    'praca principal',
                    'perto da praça',
                    'perto da praca',
                ],
                'bairros' => ['Centro', 'Vila Lenzi'],
                'city' => 'Jaraguá do Sul',
            ],
            'calcadao' => [
                'aliases' => [
                    'calçadão',
                    'calcadao',
                    'rua coberta',
                    'perto do calçadão',
                    'perto do calcadao',
                    'comércio',
                    'comercio',
                    'lojas',
                    'centro comercial',
                ],
                'bairros' => ['Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'cemiterio' => [
                'aliases' => [
                    'cemitério',
                    'cemiterio',
                    'cemitério municipal',
                    'cemiterio municipal',
                    'perto do cemitério',
                    'perto do cemiterio',
                ],
                'bairros' => ['Centro', 'Nova Brasília'],
                'city' => 'Jaraguá do Sul',
            ],
            'guarda_municipal' => [
                'aliases' => [
                    'guarda municipal',
                    'guarda',
                    'perto da guarda',
                ],
                'bairros' => ['Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'creci' => [
                'aliases' => [
                    'creci',
                    'conselho de corretores',
                    'creci sc',
                    'delegacia creci',
                    'perto do creci',
                ],
                'bairros' => ['Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'acijs' => [
                'aliases' => [
                    'acijs',
                    'associação empresarial',
                    'associacao empresarial',
                    'associação comercial',
                    'associacao comercial',
                    'perto da acijs',
                ],
                'bairros' => ['Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'grande_centro' => [
                'aliases' => [
                    'grande centro',
                    'região central ampla',
                    'regiao central ampla',
                    'arredores do centro',
                    'proximidades centro',
                ],
                'bairros' => [
                    'Centro',
                    'Vila Lenzi',
                    'Nova Brasília',
                    'Czerniewicz',
                    'Vila Baependi',
                    'Vila Lalau',
                    'Jaraguá Esquerdo',
                ],
                'city' => 'Jaraguá do Sul',
            ],
            'menegotti' => [
                'aliases' => [
                    'menegotti',
                    'metalúrgica menegotti',
                    'metalurgica menegotti',
                    'empresa menegotti',
                    'fábrica menegotti',
                    'fabrica menegotti',
                    'perto da menegotti',
                ],
                'bairros' => ['Rau', 'Centro'],
                'city' => 'Jaraguá do Sul',
            ],
            'csm' => [
                'aliases' => [
                    'csm',
                    'empresa csm',
                    'equipamentos csm',
                    'fábrica csm',
                    'fabrica csm',
                    'perto da csm',
                ],
                'bairros' => ['Rau', 'Centro'],
                'city' => 'Jaraguá do Sul',
            ],
        ],
        'joinville' => [
            'centro' => [
                'aliases' => ['centro', 'região central', 'regiao central', 'perto do centro'],
                'bairros' => ['Centro', 'América', 'Bucarein', 'Atiradores', 'Anita Garibaldi'],
                'city' => 'Joinville',
            ],
            'udesc' => [
                'aliases' => ['udesc', 'universidade do estado', 'campus udesc'],
                'bairros' => ['Bom Retiro', 'América'],
                'city' => 'Joinville',
            ],
            'shopping_mueller' => [
                'aliases' => ['shopping mueller', 'mueller'],
                'bairros' => ['América', 'Centro'],
                'city' => 'Joinville',
            ],
        ],
        'curitiba' => [
            'centro' => [
                'aliases' => ['centro', 'região central', 'regiao central', 'perto do centro'],
                'bairros' => ['Centro', 'São Francisco', 'Batel', 'Rebouças'],
                'city' => 'Curitiba',
            ],
        ],
    ],

    'radius_km' => [
        'muito_perto' => 1,
        'perto' => 2,
        'regiao' => 4,
        'distante' => 8,
        'cidade' => 15,
    ],
];
