from __future__ import annotations


RAW_PROPERTY_COLUMNS = [
    "crawler_run_id",
    "source_url",
    "external_id",
    "tipo_imovel",
    "imagem",
    "quartos",
    "sala",
    "banheiros",
    "suites",
    "vagas",
    "ano",
    "valor",
    "area_privada",
    "area_util",
    "detalhes",
    "bairro",
    "cidade",
    "piscina",
    "churrasqueira",
    "academia",
    "salao_festas",
    "playground",
    "sacada",
    "mobiliado",
    "ar_condicionado",
    "lavanderia",
    "escritorio",
    "closet",
    "elevador",
    "portaria_24h",
    "aceita_permuta",
    "financiamento",
    "raw_payload",
]


MARKET_PROPERTY_COLUMNS = [
    "crawler_run_id",
    "raw_property_id",
    "source_url",
    "tipo",
    "imobiliaria",
    "valor",
    "bairro",
    "cidade",
    "imagem",
    "link_imovel",
    "descricao",
    "quartos",
    "suites",
    "banheiros",
    "vagas",
    "area",
    "aceita_permuta",
    "financiamento",
    "piscina",
    "churrasqueira",
    "academia",
    "salao_festas",
    "playground",
    "sacada",
    "mobiliado",
    "ar_condicionado",
    "lavanderia",
    "escritorio",
    "closet",
    "elevador",
    "portaria_24h",
    "andar",
    "posicao_solar",
    "ano_construcao",
    "quality_status",
    "quality_metadata",
]


BOOLEAN_FIELDS = {
    "aceita_permuta",
    "financiamento",
    "piscina",
    "churrasqueira",
    "academia",
    "salao_festas",
    "playground",
    "sacada",
    "mobiliado",
    "ar_condicionado",
    "lavanderia",
    "escritorio",
    "closet",
    "elevador",
    "portaria_24h",
}
