<?php

use App\Services\Crawler\CrawlerPartitionManager;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
            CREATE TABLE crawler.quality_policy_versions (
                id BIGSERIAL PRIMARY KEY,
                version INTEGER NOT NULL UNIQUE,
                status VARCHAR(32) NOT NULL,
                rules JSONB NOT NULL DEFAULT '{}',
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            INSERT INTO crawler.quality_policy_versions (version, status, rules)
            VALUES (1, 'active', '{"minimum_valid_records":1,"maximum_error_ratio":0.30}');

            CREATE TABLE crawler.crawl_runs (
                id BIGSERIAL PRIMARY KEY,
                operation_id BIGINT UNIQUE REFERENCES crawler.operations(id),
                crawl_agency_id BIGINT REFERENCES crawler.crawl_agencies(id),
                discovery_snapshot_id BIGINT REFERENCES crawler.discovery_snapshots(id),
                extraction_profile_id BIGINT REFERENCES crawler.extraction_profiles(id),
                market_data_contract_version_id BIGINT REFERENCES crawler.market_data_contract_versions(id),
                quality_policy_version_id BIGINT REFERENCES crawler.quality_policy_versions(id),
                technical_state VARCHAR(32) NOT NULL DEFAULT 'running',
                result_kind VARCHAR(32) NOT NULL DEFAULT 'full',
                publication_state VARCHAR(32) NOT NULL DEFAULT 'candidate',
                publishable BOOLEAN NOT NULL DEFAULT FALSE,
                raw_count INTEGER NOT NULL DEFAULT 0,
                normalized_count INTEGER NOT NULL DEFAULT 0,
                rejected_count INTEGER NOT NULL DEFAULT 0,
                error_count INTEGER NOT NULL DEFAULT 0,
                error_summary JSONB NOT NULL DEFAULT '[]',
                started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                completed_at TIMESTAMPTZ,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT crawl_run_technical_state_check CHECK (technical_state IN ('running', 'succeeded', 'failed', 'cancelled')),
                CONSTRAINT crawl_run_result_kind_check CHECK (result_kind IN ('full', 'partial')),
                CONSTRAINT crawl_run_publication_state_check CHECK (publication_state IN ('candidate', 'quarantined', 'published'))
            );
            CREATE INDEX crawl_runs_agency_created_idx ON crawler.crawl_runs (crawl_agency_id, created_at DESC);

            CREATE TABLE crawler.raw_properties (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                crawler_run_id BIGINT NOT NULL REFERENCES crawler.crawl_runs(id),
                url TEXT,
                payload JSONB NOT NULL,
                extraction_trace JSONB NOT NULL DEFAULT '{}',
                errors JSONB NOT NULL DEFAULT '[]',
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                PRIMARY KEY (id, created_at)
            ) PARTITION BY RANGE (created_at);

            CREATE TABLE crawler.market_properties (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                crawler_run_id BIGINT NOT NULL REFERENCES crawler.crawl_runs(id),
                raw_property_id BIGINT,
                tipo VARCHAR(255), imobiliaria VARCHAR(255), valor NUMERIC(15,2),
                bairro VARCHAR(255), cidade VARCHAR(255), imagem TEXT, link_imovel TEXT,
                descricao TEXT, quartos INTEGER, suites INTEGER, banheiros INTEGER,
                vagas INTEGER, area NUMERIC(12,2), aceita_permuta BOOLEAN,
                financiamento BOOLEAN, piscina BOOLEAN, churrasqueira BOOLEAN,
                academia BOOLEAN, salao_festas BOOLEAN, playground BOOLEAN, sacada BOOLEAN,
                mobiliado BOOLEAN, ar_condicionado BOOLEAN, lavanderia BOOLEAN,
                escritorio BOOLEAN, closet BOOLEAN, elevador BOOLEAN, portaria_24h BOOLEAN,
                andar VARCHAR(255), posicao_solar VARCHAR(255), ano_construcao INTEGER,
                payload JSONB NOT NULL,
                normalization_warnings JSONB NOT NULL DEFAULT '[]',
                extraction_trace JSONB NOT NULL DEFAULT '{}',
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                PRIMARY KEY (id, created_at)
            ) PARTITION BY RANGE (created_at);

            CREATE TABLE crawler.rejected_properties (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                crawler_run_id BIGINT NOT NULL REFERENCES crawler.crawl_runs(id),
                raw_property_id BIGINT,
                url TEXT,
                payload JSONB NOT NULL,
                missing_fields JSONB NOT NULL DEFAULT '[]',
                errors JSONB NOT NULL DEFAULT '[]',
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                PRIMARY KEY (id, created_at)
            ) PARTITION BY RANGE (created_at);

            CREATE TABLE crawler.crawler_artifacts (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                crawler_run_id BIGINT NOT NULL REFERENCES crawler.crawl_runs(id),
                kind VARCHAR(64) NOT NULL,
                payload JSONB NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                PRIMARY KEY (id, created_at)
            ) PARTITION BY RANGE (created_at);

            CREATE TABLE crawler.technical_logs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                crawler_run_id BIGINT NOT NULL REFERENCES crawler.crawl_runs(id),
                level VARCHAR(16) NOT NULL,
                stage VARCHAR(64),
                message TEXT NOT NULL,
                context JSONB NOT NULL DEFAULT '{}',
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                PRIMARY KEY (id, created_at)
            ) PARTITION BY RANGE (created_at);

            CREATE INDEX raw_properties_run_idx ON crawler.raw_properties (crawler_run_id, created_at DESC);
            CREATE INDEX market_properties_run_idx ON crawler.market_properties (crawler_run_id, created_at DESC);
            CREATE INDEX market_properties_search_idx ON crawler.market_properties (cidade, bairro, valor);
            CREATE INDEX rejected_properties_run_idx ON crawler.rejected_properties (crawler_run_id, created_at DESC);
            CREATE INDEX crawler_artifacts_run_idx ON crawler.crawler_artifacts (crawler_run_id, created_at DESC);
            CREATE INDEX technical_logs_run_idx ON crawler.technical_logs (crawler_run_id, created_at DESC);
        SQL);

        app(CrawlerPartitionManager::class)->ensureMonths(now()->startOfMonth(), 4);
        app(CrawlerPartitionManager::class)->ensureDefaultPartitions();
    }

    public function down(): void
    {
        DB::unprepared(<<<'SQL'
            DROP TABLE IF EXISTS crawler.technical_logs CASCADE;
            DROP TABLE IF EXISTS crawler.crawler_artifacts CASCADE;
            DROP TABLE IF EXISTS crawler.rejected_properties CASCADE;
            DROP TABLE IF EXISTS crawler.market_properties CASCADE;
            DROP TABLE IF EXISTS crawler.raw_properties CASCADE;
            DROP TABLE IF EXISTS crawler.crawl_runs CASCADE;
            DROP TABLE IF EXISTS crawler.quality_policy_versions CASCADE;
        SQL);
    }
};
