import type { OnboardingExecution } from "@/types/crawler";

export function onboardingExecution(
  overrides: Partial<OnboardingExecution> = {},
): OnboardingExecution {
  return {
    id: 91,
    onboarding_plan_id: 14,
    crawl_agency_id: 42,
    name: "Onboarding Litoral",
    conduction: "automated",
    state: "running",
    current_step: "discovery",
    execution_model_version_id: 13,
    discovery_policy_version_id: 11,
    extraction_policy_version_id: 12,
    discovery_snapshot_id: null,
    market_data_contract_version_id: 1,
    extraction_profile_id: null,
    profile_validation_report_id: null,
    first_production_discovery_mode: "fresh",
    first_production_crawl_run_id: null,
    created_by: { id: 1, name: "Operator" },
    resolved_configuration: {
      version: 1,
      execution_model: { id: 13, name: "Modelo", version: 1 },
      discovery: { mode: "fresh" },
      discovery_policy: { id: 11, name: "Discovery", version: 1, source: "catalog", strategies: ["sitemap"], configuration: {} },
      extraction_policy: { id: 12, name: "Extração", version: 1, source: "catalog", strategies: ["xpath"], configuration: {} },
      market_data_contract: { id: 1, version: 1, fields: [] },
    },
    sample_url: null,
    sample_url_selection: null,
    attention: null,
    approval: null,
    first_production: null,
    steps: [
      { key: "discovery", state: "running", operation_id: 101, attempt: 1 },
      { key: "profile_generation", state: "pending", operation_id: null, attempt: null },
      { key: "profile_validation", state: "pending", operation_id: null, attempt: null },
      { key: "approval", state: "pending", operation_id: null, attempt: null },
      { key: "first_production", state: "pending", operation_id: null, attempt: null },
      { key: "quality_gate", state: "pending", operation_id: null, attempt: null },
    ],
    operations: [{
      id: 101,
      type: "discovery",
      state: "running",
      step: "discovery",
      attempt: 1,
      retry_of_operation_id: null,
      progress: { stage: "discovery", percentage: 45, message: "Buscando URLs" },
      result: null,
      error: null,
      created_at: "2026-07-27T12:00:00Z",
      completed_at: null,
    }],
    recovery_actions: [],
    next_action: "wait_for_current_operation",
    started_at: "2026-07-27T12:00:00Z",
    paused_at: null,
    completed_at: null,
    created_at: "2026-07-27T12:00:00Z",
    updated_at: "2026-07-27T12:01:00Z",
    ...overrides,
  };
}
